version: '3'
services:
  postDb:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  database-data: